version: "3.7"
services:
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:latest
    environment:
    - "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=couchbase-couchbase"
    - "GF_PLUGIN_APP_TLS_SKIP_VERIFY_INSECURE=true"
    volumes:
    - .:/var/lib/grafana/plugins
    ports:
    - "3000:3000"
    expose:
    - 3000
