{
 "title": "Example Couchbase Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "General Information",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select sum(count) as sum, count(count) as records from test where str_time_range(time)"
    }
   ]
  },
  {
   "title": "String distribution",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select sum(tdd.count), tdd.content as content from test as tdd\n  WHERE STR_TIME_RANGE(time)\n  GROUP BY tdd.content"
    }
   ]
  },
  {
   "title": "Distribution of values",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select max(count) as max, min(count) as min, avg(count) as avg from test\n  WHERE STR_TIME_RANGE(time)"
    }
   ]
  },
  {
   "title": "All data",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "select tdd.count, tdd.time from test as tdd\n  WHERE STR_TIME_RANGE(time)"
    }
   ]
  },
  {
   "title": "Log10 of Sum per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "select LOG(SUM(tdd.count)) as sum, count(tdd.time) as count, date_trunc_str(tdd.time, 'minute') as time from test as tdd\n  WHERE STR_TIME_RANGE(time)\n  GROUP BY date_trunc_str(tdd.time, 'minute')"
    }
   ]
  }
 ]
}