name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: couchbase-datasource

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"

      - name: Cache yarn cache
        uses: actions/cache@v4
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('couchbase-datasource/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: couchbase-datasource/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('couchbase-datasource/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck frontend
        run: yarn typecheck

      - name: Test frontend
        run: yarn test:ci

      - name: Build frontend
        run: yarn build

      - name: Check for backend
        id: check-for-backend
        run: |
          if [ -f "Magefile.go" ]
          then
            echo "has-backend=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Go environment
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@v5
        with:
          go-version-file: couchbase-datasource/go.mod

      - name: Test backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: coverage
          workdir: couchbase-datasource

      - name: Build backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: buildAll
          workdir: couchbase-datasource
