name: Release

on:
  push:
    tags:
      - "v*.*.*" # Run workflow on version tags, e.g. v1.0.0.
  workflow_dispatch:

jobs:
  release:
    name: Build and upload Grafana Docker Repo
    runs-on: ubuntu-latest
    env:
      IMAGE_URL: ${{ secrets.IMAGE_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-west-1
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - name: Build the app
        run: ./release.sh
      - name: Build and push docker image
        run:  |
          docker build plugins -t "${IMAGE_URL}:${GITHUB_SHA::6}" -t "${IMAGE_URL}:latest"
          docker push "${IMAGE_URL}:${GITHUB_SHA::6}"
          docker push "${IMAGE_URL}:latest"

